server:
  port: 9000

spring:
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat